classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: pipelines.imu.readers.CustomDataReader

coords:
  time:
    name: time
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: UTC
  direction:
    name: space

data_vars:
  roll:
    name: roll
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: radians
  pitch:
    name: pitch
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: radians
  yaw:
    name: yaw
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: radians
  angular_velocity:
    name: gyro
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: radians
  acceleration:
    name: accel
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: radians
  magnetic_field:
    name: mag
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: gauss
  pressure:
    name: pres
