attrs:
  title: "Metocean Buoy Pipeline"
  description:
    Ingest of metocean data from an AXYS Technologies buoy stationed in Morro Bay, CA
  location_id: morro
  dataset_name: buoy_z06
  data_level: a1
  qualifier: metocean
  temporal: 10m
  instrument_manufacturer: "AXYS Technologies Inc."
  instrument_name: "WindSentinel"

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00

  depth:
    dims: [depth]
    dtype: long
    attrs:
      long_name: Depth
      units: m

data_vars:
  CTD_SST:
    dims: [time]
    dtype: float
    attrs:
      long_name: Sea surface temperature
      units: degC
      fail_range: [-5, 45]

  conductivity:
    dims: [time]
    dtype: float
    attrs:
      long_name: Ocean Conductivity
      units: S/m
      fail_range: [0, 7]

  currents_bin_spacing:
    dims: [time]
    dtype: float
    attrs:
      long_name: Vertical Spacing Between Bins
      units: m

  currents_head_depth:
    dims: [time]
    dtype: float
    attrs:
      long_name: depth of instrument below ocean surface
      units: m

  currents_blanking_distance:
    dims: [time]
    dtype: float
    attrs:
      long_name: Blanking Distance
      comment:
        a "blind zone" where the instruments do not measure anything. Typically less
        than 1m.
      units: m

  # This is a computed value, but the computation is now done in
  # a hook prior to dataset standardization, so it is considered
  # to have input.
  current_speed:
    dtype: float
    dims: [time, depth]
    attrs:
      long_name: Current Speed
      units: mm/s
      fail_range: [0, 10000]

  # This is a computed value, but the computation is now done in
  # a hook prior to dataset standardization, so it is considered
  # to have input.
  current_direction:
    dtype: float
    dims: [time, depth]
    attrs:
      long_name: Current Direction
      units: degrees
      fail_range: [0, 360]

  wind_speed_gill:
    dims: [time]
    dtype: float
    attrs:
      long_name: Horizontal Wind Speed
      comment: Surface horizontal wind speed, 2D ultrasonic anemometer
      units: m/s
      fail_range: [0, 50]

  wind_direction_gill:
    dims: [time]
    dtype: float
    attrs:
      long_name: Horizontal Wind Direction
      comment: Surface horizontal wind direction, 2D ultrasonic anemometer
      units: degrees
      fail_range: [0, 360]

  wind_speed:
    dims: [time]
    dtype: float
    attrs:
      long_name: Horizontal Wind Speed
      comment: Surface wind speed, cup anemometer
      units: m/s
      fail_range: [0, 50]

  wind_direction:
    dims: [time]
    dtype: float
    attrs:
      long_name: Horizontal Wind Direction
      comment: Surface wind direction, wind vane
      units: degrees
      fail_range: [0, 360]

  pressure:
    dims: [time]
    dtype: float
    attrs:
      long_name: Atmospheric Pressure
      units: hPa
      fail_range: [500, 1100]

  relative_humidity:
    dims: [time]
    dtype: float
    attrs:
      long_name: Relative Humidity
      units: "%"
      fail_range: [0, 100]

  # Note that this variable had the same name as Surface Temperature from
  # conductivity csv. It has been renamed to prevent a conflict, but the
  # user will need to write the customize_raw_dataset() hook to rename the
  # raw input from "Surface Temperature (C)" to "surfacetemp - Surface
  # Temperature (C)" so that the code can still retrieve it properly
  sea_surface_temperature:
    dims: [time]
    dtype: float
    attrs:
      long_name: Sea Surface Temperature
      comment: This is from the surfacetemp.csv file.
      units: degC
      fail_range: [-5, 50]

  air_temperature:
    dims: [time]
    dtype: float
    attrs:
      long_name: Air Temperature
      units: degC
      fail_range: [-40, 60]

  latitude:
    dims: [time]
    dtype: float
    attrs:
      long_name: Latitude
      units: degree_N

  longitude:
    dims: [time]
    dtype: float
    attrs:
      long_name: Longitude
      units: degree_E
