classname: pipelines.metocean.pipeline.Metocean

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*morro.*\.csv

retriever:
  path: pipelines/metocean/config/retriever.yaml

dataset:
  path: pipelines/metocean/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
