classname: tsdat.io.retrievers.DefaultRetriever
readers:
  .*:
    classname: tsdat.io.readers.ZipReader
    parameters:
      readers:
        buoy:
          classname: pipelines.metocean.readers.BuoyReader

coords:
  time:
    name: DataTimeStamp
    data_converters:
      - classname: tsdat.io.converters.StringToDatetime
        format: "%Y-%m-%d %H:%M:%S"
        timezone: UTC
  depth:
    name: depth

data_vars:
  sea_surface_temperature_CTD:
    name: "Surface Temperature (C)"
  conductivity:
    name: "Conductivity (Siemens/m)"
  current_speed:
    name: current_speed
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: mm/s
  current_direction:
    name: current_direction
  wind_speed_gill:
    name: gill_horizontal_wind_speed
  wind_direction_gill:
    name: gill_horizontal_wind_direction
  wind_speed:
    name: Horizontal Speed (m/s)
  wind_direction:
    name: Horizontal Direction (deg)
  pressure:
    name: Barometric Pressure (mb)
    data_converters:
      - classname: tsdat.io.converters.UnitsConverter
        input_units: mbar
  solar_radiation:
    name: Solar Radiation (W/m^2)
  relative_humidity:
    name: Relative Humidity (%)
  sea_surface_temperature_YSI:
    name: surfacetemp - Surface Temperature (C)
  air_temperature:
    name: Air Temperature (C)
  latitude:
    name: Latitude
  longitude:
    name: Longitude
