classname: pipelines.lidar.pipeline.Lidar

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*morro.*\.csv

retriever:
  path: pipelines/lidar/config/retriever.yaml

dataset:
  path: pipelines/lidar/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
